/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTagsRouteImport } from './routes/_app.tags'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMovementsRouteImport } from './routes/_app.movements'
import { Route as AppMapRouteImport } from './routes/_app.map'
import { Route as AppInspectionsRouteImport } from './routes/_app.inspections'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppTreesIndexRouteImport } from './routes/_app.trees.index'
import { Route as AppRegionsIndexRouteImport } from './routes/_app.regions.index'
import { Route as AppTreesRegisterRouteImport } from './routes/_app.trees.register'
import { Route as AppTreesTagIdRouteImport } from './routes/_app.trees.$tagId'
import { Route as AppRegionsIdRouteImport } from './routes/_app.regions.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsRoute = AppMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionsRoute = AppInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppTreesIndexRoute = AppTreesIndexRouteImport.update({
  id: '/trees/',
  path: '/trees/',
  getParentRoute: () => AppRoute,
} as any)
const AppRegionsIndexRoute = AppRegionsIndexRouteImport.update({
  id: '/regions/',
  path: '/regions/',
  getParentRoute: () => AppRoute,
} as any)
const AppTreesRegisterRoute = AppTreesRegisterRouteImport.update({
  id: '/trees/register',
  path: '/trees/register',
  getParentRoute: () => AppRoute,
} as any)
const AppTreesTagIdRoute = AppTreesTagIdRouteImport.update({
  id: '/trees/$tagId',
  path: '/trees/$tagId',
  getParentRoute: () => AppRoute,
} as any)
const AppRegionsIdRoute = AppRegionsIdRouteImport.update({
  id: '/regions/$id',
  path: '/regions/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/inspections': typeof AppInspectionsRoute
  '/map': typeof AppMapRoute
  '/movements': typeof AppMovementsRoute
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/tags': typeof AppTagsRoute
  '/users': typeof AppUsersRoute
  '/regions/$id': typeof AppRegionsIdRoute
  '/trees/$tagId': typeof AppTreesTagIdRoute
  '/trees/register': typeof AppTreesRegisterRoute
  '/regions/': typeof AppRegionsIndexRoute
  '/trees/': typeof AppTreesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/inspections': typeof AppInspectionsRoute
  '/map': typeof AppMapRoute
  '/movements': typeof AppMovementsRoute
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/tags': typeof AppTagsRoute
  '/users': typeof AppUsersRoute
  '/regions/$id': typeof AppRegionsIdRoute
  '/trees/$tagId': typeof AppTreesTagIdRoute
  '/trees/register': typeof AppTreesRegisterRoute
  '/regions': typeof AppRegionsIndexRoute
  '/trees': typeof AppTreesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inspections': typeof AppInspectionsRoute
  '/_app/map': typeof AppMapRoute
  '/_app/movements': typeof AppMovementsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tags': typeof AppTagsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/regions/$id': typeof AppRegionsIdRoute
  '/_app/trees/$tagId': typeof AppTreesTagIdRoute
  '/_app/trees/register': typeof AppTreesRegisterRoute
  '/_app/regions/': typeof AppRegionsIndexRoute
  '/_app/trees/': typeof AppTreesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/dashboard'
    | '/inspections'
    | '/map'
    | '/movements'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/tags'
    | '/users'
    | '/regions/$id'
    | '/trees/$tagId'
    | '/trees/register'
    | '/regions/'
    | '/trees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit'
    | '/dashboard'
    | '/inspections'
    | '/map'
    | '/movements'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/tags'
    | '/users'
    | '/regions/$id'
    | '/trees/$tagId'
    | '/trees/register'
    | '/regions'
    | '/trees'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/audit'
    | '/_app/dashboard'
    | '/_app/inspections'
    | '/_app/map'
    | '/_app/movements'
    | '/_app/notifications'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/tags'
    | '/_app/users'
    | '/_app/regions/$id'
    | '/_app/trees/$tagId'
    | '/_app/trees/register'
    | '/_app/regions/'
    | '/_app/trees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tags': {
      id: '/_app/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movements': {
      id: '/_app/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof AppMovementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspections': {
      id: '/_app/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AppInspectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trees/': {
      id: '/_app/trees/'
      path: '/trees'
      fullPath: '/trees/'
      preLoaderRoute: typeof AppTreesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/regions/': {
      id: '/_app/regions/'
      path: '/regions'
      fullPath: '/regions/'
      preLoaderRoute: typeof AppRegionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trees/register': {
      id: '/_app/trees/register'
      path: '/trees/register'
      fullPath: '/trees/register'
      preLoaderRoute: typeof AppTreesRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trees/$tagId': {
      id: '/_app/trees/$tagId'
      path: '/trees/$tagId'
      fullPath: '/trees/$tagId'
      preLoaderRoute: typeof AppTreesTagIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/regions/$id': {
      id: '/_app/regions/$id'
      path: '/regions/$id'
      fullPath: '/regions/$id'
      preLoaderRoute: typeof AppRegionsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInspectionsRoute: typeof AppInspectionsRoute
  AppMapRoute: typeof AppMapRoute
  AppMovementsRoute: typeof AppMovementsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTagsRoute: typeof AppTagsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppRegionsIdRoute: typeof AppRegionsIdRoute
  AppTreesTagIdRoute: typeof AppTreesTagIdRoute
  AppTreesRegisterRoute: typeof AppTreesRegisterRoute
  AppRegionsIndexRoute: typeof AppRegionsIndexRoute
  AppTreesIndexRoute: typeof AppTreesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInspectionsRoute: AppInspectionsRoute,
  AppMapRoute: AppMapRoute,
  AppMovementsRoute: AppMovementsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTagsRoute: AppTagsRoute,
  AppUsersRoute: AppUsersRoute,
  AppRegionsIdRoute: AppRegionsIdRoute,
  AppTreesTagIdRoute: AppTreesTagIdRoute,
  AppTreesRegisterRoute: AppTreesRegisterRoute,
  AppRegionsIndexRoute: AppRegionsIndexRoute,
  AppTreesIndexRoute: AppTreesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
